"""v2.10 mirror 架构防回归 — 已 .gitignore 排除的路径必须 0 个 git tracked。

历史背景：v2.10 (commit 5123593, 2026-04-12) 把 mirror 加进 .gitignore +
git rm --cached，确立 "mirror = build artifact, generated by hatch_build.py /
dev_sync.py" 架构。但已 tracked 的文件不被 .gitignore 影响仍持续被追踪，
v2.10→v2.31 累积了 55 个遗留 tracked mirror（PR cleanup 把它们全 rm 了）。

本测试每 PR 跑一次，断言 .gitignore 排除的 mirror 路径与 git tracked 文件交集
= 空。下次有人误 git add mirror（绕过 .gitignore 警告或用 -f）立即 fail。
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path


_REPO_ROOT = Path(__file__).resolve().parent.parent
_GITIGNORE = _REPO_ROOT / ".gitignore"


def _parse_mirror_paths_from_gitignore() -> list[str]:
    """从 .gitignore 的 'v2.10: build-time mirrors' 段提取被排除的 mirror 路径。"""
    text = _GITIGNORE.read_text(encoding="utf-8")
    section_match = re.search(
        r"# v2\.10: build-time mirrors[^\n]*\n((?:[^\n#][^\n]*\n)+)",
        text,
    )
    assert section_match, ".gitignore 缺 v2.10 mirror 段 — 架构 invariant 丢失"
    paths: list[str] = []
    for line in section_match.group(1).splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            paths.append(stripped)
    return paths


def _git_tracked_under(path: str) -> list[str]:
    """git ls-files <path>。path 末尾 '/' 视为目录递归。"""
    result = subprocess.run(
        ["git", "ls-files", path],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=True,
    )
    return [line for line in result.stdout.splitlines() if line.strip()]


def test_v2_10_mirror_paths_have_zero_tracked_files() -> None:
    """v2.10 .gitignore 排除的 mirror 路径下不得有 git tracked 文件。"""
    mirror_paths = _parse_mirror_paths_from_gitignore()
    assert mirror_paths, ".gitignore mirror 段为空 — 解析 bug 或 section 被删"

    violations: dict[str, list[str]] = {}
    for path in mirror_paths:
        tracked = _git_tracked_under(path)
        if tracked:
            violations[path] = tracked

    assert not violations, (
        "v2.10 架构违反：以下 .gitignore 排除路径下仍有 git tracked 文件：\n"
        + "\n".join(
            f"  {path}: {len(files)} files (e.g. {files[0]})"
            for path, files in violations.items()
        )
        + "\n修法：git rm --cached <files> 让 mirror 由 hatch_build / dev_sync 生成。"
    )


def test_gitignore_v2_10_section_intact() -> None:
    """.gitignore 必须保留 v2.10 mirror 排除段（防误删）。"""
    text = _GITIGNORE.read_text(encoding="utf-8")
    required_paths = [
        "src/cad_spec_gen/data/python_tools/",
        "src/cad_spec_gen/data/codegen/",
        "src/cad_spec_gen/data/templates/",
        "src/cad_spec_gen/data/config/",
        "src/cad_spec_gen/data/tools/",
        "src/cad_spec_gen/data/commands/zh/",
    ]
    missing = [p for p in required_paths if p not in text]
    assert not missing, (
        f".gitignore 缺以下 v2.10 mirror 排除路径：{missing}\n"
        "若需修改 mirror 架构，请同步更新 hatch_build.py + dev_sync.py。"
    )
