"""
T16 螺母 C7 (SLP-C01) — 真实 STEP 导入件

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: transmission | Make/Buy: 外购
Material: —
Source: STEP:std_parts/user_provided/SLP-C01_T16_螺母_C7_4edfe101b181.step
Geometry source: REAL_STEP
Geometry quality: A
Validated: true
Hash: sha256:b610b121a0ac3fab81aa766e88639fde0a50db88073f53da6d5723bcf29eb96a
Path kind: project_relative
Requires model review: false

NOTE: Imported from a STEP model selected by parts_resolver.
      Verify upstream license and dimensional fit before manufacturing.
"""

import os
import sys
_here = os.path.dirname(os.path.abspath(__file__))
_project_root = os.path.normpath(os.path.join(_here, "..", ".."))
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

import cadquery as cq


def make_std_c01() -> cq.Workplane:
    """SLP-C01: T16 螺母 C7 — imported from STEP file.

    Source: STEP:std_parts/user_provided/SLP-C01_T16_螺母_C7_4edfe101b181.step
    """
    import os
    _here = os.path.dirname(os.path.abspath(__file__))
    _step_path = os.path.join(_here, "..", "..", 'std_parts/user_provided/SLP-C01_T16_螺母_C7_4edfe101b181.step')
    _step_path = os.path.normpath(_step_path)
    if not os.path.isfile(_step_path):
        raise FileNotFoundError(
            f"STEP file missing for SLP-C01: {_step_path}")
    _model = cq.importers.importStep(_step_path)
    _bbox = _model.val().BoundingBox()
    _origin_shift = (
        -(_bbox.xmin + _bbox.xmax) / 2.0,
        -(_bbox.ymin + _bbox.ymax) / 2.0,
        -_bbox.zmin,
    )
    return _model.translate(_origin_shift)


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_c01()
    p = os.path.join(out, "SLP-C01_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
