"""
φ5×20 定位销 (SLP-F06) — 参数化模板几何

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: locating | Make/Buy: 标准件
Material: —
Source: parametric_template:locating_pin
Geometry source: PARAMETRIC_TEMPLATE
Geometry quality: B
Validated: false
Hash: n/a
Path kind: n/a
Requires model review: false

NOTE: Generated from a curated parametric template selected by parts_resolver.
      This is not a vendor STEP model; verify dimensional fit before manufacturing.
"""

import os
import sys
_here = os.path.dirname(os.path.abspath(__file__))
_project_root = os.path.normpath(os.path.join(_here, "..", ".."))
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

import cadquery as cq


def make_std_f06() -> cq.Workplane:
    """SLP-F06: φ5×20 定位销 — parametric template geometry."""
    # Semi-parametric locating pin: precision dowel with chamfers and relief grooves
    body = cq.Workplane("XY").circle(2.5).extrude(20.0)
    for z in (2.000, 17.300):
        groove = (cq.Workplane("XY")
                  .circle(2.530)
                  .circle(2.320)
                  .extrude(0.700)
                  .translate((0, 0, z)))
        body = body.cut(groove)
    try:
        body = body.faces(">Z").edges(">Z").chamfer(0.400)
        body = body.faces("<Z").edges("<Z").chamfer(0.400)
    except Exception:
        pass
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_f06()
    p = os.path.join(out, "SLP-F06_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
