"""
LM10UU (SLP-C02) — 真实 STEP 导入件

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: bearing | Make/Buy: 外购
Material: 
Source: STEP:std_parts/user_provided/SLP-C02_LM10UU.step

NOTE: Imported from a STEP model selected by parts_resolver.
      Verify upstream license and dimensional fit before manufacturing.
"""

import cadquery as cq


def make_std_c02() -> cq.Workplane:
    """SLP-C02: LM10UU — imported from STEP file.

    Source: STEP:std_parts/user_provided/SLP-C02_LM10UU.step
    """
    import os
    _here = os.path.dirname(os.path.abspath(__file__))
    _step_path = os.path.join(_here, "..", "..", 'std_parts/user_provided/SLP-C02_LM10UU.step')
    _step_path = os.path.normpath(_step_path)
    if not os.path.isfile(_step_path):
        raise FileNotFoundError(
            f"STEP file missing for SLP-C02: {_step_path}")
    return cq.importers.importStep(_step_path)


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_c02()
    p = os.path.join(out, "SLP-C02_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
