"""
L070 联轴器 (SLP-C06) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: connector | Make/Buy: 外购
Material: 
Dimensions: {'d': 25, 'l': 30, 'bore_d': 6.35}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_c06() -> cq.Workplane:
    """SLP-C06: L070 联轴器 — simplified connector geometry."""
    # L070 clamping coupling: split cylindrical coupler with twin clamp grooves
    body = cq.Workplane("XY").circle(12.5).circle(3.175).extrude(30)
    for z in (8.400, 20.400):
        groove = (cq.Workplane("XY")
                  .circle(12.550)
                  .circle(11.700)
                  .extrude(1.800)
                  .translate((0, 0, z)))
        body = body.cut(groove)
    split = (cq.Workplane("XY")
             .box(3.000, 25.200, 30.200, centered=(True, True, False))
             .translate((8.000, 0, -0.1)))
    body = body.cut(split)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_c06()
    p = os.path.join(out, "SLP-C06_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
