"""
PU 缓冲垫 20×20×3 (SLP-F11) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: seal | Make/Buy: 外购
Material: 
Dimensions: {'od': 80, 'id': 75, 'section_d': 2.4}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_f11() -> cq.Workplane:
    """SLP-F11: PU 缓冲垫 20×20×3 — simplified seal geometry."""
    # Simplified O-ring: torus
    path = cq.Workplane("XY").circle(38.75)
    body = (cq.Workplane("XZ")
            .center(38.75, 0)
            .circle(1.2)
            .sweep(path))
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_f11()
    p = os.path.join(out, "SLP-F11_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
