"""
导向轴保护帽 φ10 (SLP-F13) — 参数化模板几何

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: other | Make/Buy: 外购
Material: 
Source: parametric_template:guide_shaft_protective_cap

NOTE: Generated from a curated parametric template selected by parts_resolver.
      This is not a vendor STEP model; verify dimensional fit before manufacturing.
"""

import cadquery as cq


def make_std_f13() -> cq.Workplane:
    """SLP-F13: 导向轴保护帽 φ10 — parametric template geometry."""
    # guide shaft protective cap: closed cylindrical end cap with shaft pocket
    body = cq.Workplane("XY").circle(5.0).extrude(8)
    pocket = cq.Workplane("XY").circle(3.500).extrude(5.760)
    body = body.cut(pocket)
    lip = (cq.Workplane("XY")
           .circle(5.000)
           .circle(4.175)
           .extrude(1.440))
    body = body.union(lip)
    for z in (2.400, 4.160):
        grip = (cq.Workplane("XY")
                .circle(5.020)
                .circle(4.550)
                .extrude(0.640)
                .translate((0, 0, z)))
        body = body.cut(grip)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_f13()
    p = os.path.join(out, "SLP-F13_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
