"""
NEMA23 闭环步进 ≥1.0Nm (SLP-C07) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: motor | Make/Buy: 外购
Material: 
Dimensions: {'d': 22, 'l': 50, 'shaft_d': 4, 'shaft_l': 12}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_c07() -> cq.Workplane:
    """SLP-C07: NEMA23 闭环步进 ≥1.0Nm — simplified motor geometry."""
    # Simplified motor: cylinder + shaft
    body = cq.Workplane("XY").circle(11.0).extrude(50)
    # Output shaft
    body = body.faces(">Z").workplane().circle(2.0).extrude(12)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_c07()
    p = os.path.join(out, "SLP-C07_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
