"""
GT2 20T 开式带轮 φ12 (SLP-C04) — 真实 STEP 导入件

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: transmission | Make/Buy: 外购
Material: —
Source: STEP:cache://transmission/gt2_20t_timing_pulley.step
Geometry source: REAL_STEP
Geometry quality: A
Validated: true
Hash: sha256:19acab231e838749b4ad6f56d137b7339f2d725260b6df761611866e106e2313
Path kind: shared_cache
Requires model review: false

NOTE: Imported from a STEP model selected by parts_resolver.
      Verify upstream license and dimensional fit before manufacturing.
"""

import cadquery as cq


def make_std_c04() -> cq.Workplane:
    """SLP-C04: GT2 20T 开式带轮 φ12 — imported from STEP file.

    Source: STEP:cache://transmission/gt2_20t_timing_pulley.step
    """
    import os
    _here = os.path.dirname(os.path.abspath(__file__))
    _cache_rel = 'transmission/gt2_20t_timing_pulley.step'
    _cache_root = os.environ.get("CAD_SPEC_GEN_STEP_CACHE")
    if _cache_root:
        _step_path = os.path.join(os.path.expanduser(_cache_root), _cache_rel)
    else:
        from pathlib import Path
        _step_path = os.path.join(str(Path.home()), ".cad-spec-gen", "step_cache", _cache_rel)
    _step_path = os.path.normpath(_step_path)
    if not os.path.isfile(_step_path):
        raise FileNotFoundError(
            f"STEP file missing for SLP-C04: {_step_path}")
    _model = cq.importers.importStep(_step_path)
    _bbox = _model.val().BoundingBox()
    _origin_shift = (
        -(_bbox.xmin + _bbox.xmax) / 2.0,
        -(_bbox.ymin + _bbox.ymax) / 2.0,
        -_bbox.zmin,
    )
    return _model.translate(_origin_shift)


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_c04()
    p = os.path.join(out, "SLP-C04_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
