"""
M8 电感接近开关 NPN-NO (SLP-F12) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: sensor | Make/Buy: 外购
Material: 
Dimensions: {'d': 15, 'l': 12}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_f12() -> cq.Workplane:
    """SLP-F12: M8 电感接近开关 NPN-NO — simplified sensor geometry."""
    # Simplified sensor: cylinder
    body = cq.Workplane("XY").circle(7.5).extrude(12)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_f12()
    p = os.path.join(out, "SLP-F12_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
