"""
PU 缓冲垫 20×20×3 (SLP-F11) — 真实 STEP 导入件

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: seal | Make/Buy: 外购
Material: —
Source: STEP:cache://elastomer/pu_buffer_pad_20x20x3.step
Geometry source: REAL_STEP
Geometry quality: A
Validated: true
Hash: sha256:f884caee24eeb2fb3b5b345a3b2fb9941db8aebc34a8d955f290c4524b443906
Path kind: shared_cache
Requires model review: false

NOTE: Imported from a STEP model selected by parts_resolver.
      Verify upstream license and dimensional fit before manufacturing.
"""

import cadquery as cq


def make_std_f11() -> cq.Workplane:
    """SLP-F11: PU 缓冲垫 20×20×3 — imported from STEP file.

    Source: STEP:cache://elastomer/pu_buffer_pad_20x20x3.step
    """
    import os
    _here = os.path.dirname(os.path.abspath(__file__))
    _cache_rel = 'elastomer/pu_buffer_pad_20x20x3.step'
    _cache_root = os.environ.get("CAD_SPEC_GEN_STEP_CACHE")
    if _cache_root:
        _step_path = os.path.join(os.path.expanduser(_cache_root), _cache_rel)
    else:
        from pathlib import Path
        _step_path = os.path.join(str(Path.home()), ".cad-spec-gen", "step_cache", _cache_rel)
    _step_path = os.path.normpath(_step_path)
    if not os.path.isfile(_step_path):
        raise FileNotFoundError(
            f"STEP file missing for SLP-F11: {_step_path}")
    _model = cq.importers.importStep(_step_path)
    _bbox = _model.val().BoundingBox()
    _origin_shift = (
        -(_bbox.xmin + _bbox.xmax) / 2.0,
        -(_bbox.ymin + _bbox.ymax) / 2.0,
        -_bbox.zmin,
    )
    return _model.translate(_origin_shift)


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_f11()
    p = os.path.join(out, "SLP-F11_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
