"""
KFL001 (SLP-C03) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: bearing | Make/Buy: 外购
Material: 
Dimensions: {'od': 12, 'id': 6, 'w': 4}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_c03() -> cq.Workplane:
    """SLP-C03: KFL001 — simplified bearing geometry."""
    # Simplified bearing: outer ring + inner ring + gap
    outer = cq.Workplane("XY").circle(6.0).circle(5.0).extrude(4)
    inner = cq.Workplane("XY").circle(4.0).circle(3.0).extrude(4)
    body = outer.union(inner)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_c03()
    p = os.path.join(out, "SLP-C03_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
