"""
L070 联轴器 (SLP-C06) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: connector | Make/Buy: 外购
Material: 
Dimensions: {'d': 10, 'l': 25}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_c06() -> cq.Workplane:
    """SLP-C06: L070 联轴器 — simplified connector geometry."""
    # Simplified round connector
    body = cq.Workplane("XY").circle(5.0).extrude(25)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_c06()
    p = os.path.join(out, "SLP-C06_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
