"""
PU 缓冲垫 20×20×3 (SLP-F11) — 真实 STEP 导入件

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: seal | Make/Buy: 外购
Material: —
Source: STEP:std_parts/user_provided/SLP-F11_PU_缓冲垫_20_20_3_f884caee24ee.step
Geometry source: REAL_STEP
Geometry quality: A
Validated: true
Hash: sha256:f884caee24eeb2fb3b5b345a3b2fb9941db8aebc34a8d955f290c4524b443906
Path kind: project_relative
Requires model review: false

NOTE: Imported from a STEP model selected by parts_resolver.
      Verify upstream license and dimensional fit before manufacturing.
"""

import os
import sys
_here = os.path.dirname(os.path.abspath(__file__))
_project_root = os.path.normpath(os.path.join(_here, "..", ".."))
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

import cadquery as cq


def make_std_f11() -> cq.Workplane:
    """SLP-F11: PU 缓冲垫 20×20×3 — imported from STEP file.

    Source: STEP:std_parts/user_provided/SLP-F11_PU_缓冲垫_20_20_3_f884caee24ee.step
    """
    import os
    _here = os.path.dirname(os.path.abspath(__file__))
    _step_path = os.path.join(_here, "..", "..", 'std_parts/user_provided/SLP-F11_PU_缓冲垫_20_20_3_f884caee24ee.step')
    _step_path = os.path.normpath(_step_path)
    if not os.path.isfile(_step_path):
        raise FileNotFoundError(
            f"STEP file missing for SLP-F11: {_step_path}")
    _model = cq.importers.importStep(_step_path)
    _bbox = _model.val().BoundingBox()
    _origin_shift = (
        -(_bbox.xmin + _bbox.xmax) / 2.0,
        -(_bbox.ymin + _bbox.ymax) / 2.0,
        -_bbox.zmin,
    )
    return _model.translate(_origin_shift)


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_f11()
    p = os.path.join(out, "SLP-F11_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
