"""
KFL001 (SLP-C03) — 真实 STEP 导入件

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: bearing | Make/Buy: 外购
Material: —
Source: STEP:cache://mechanical/kfl001_flange_bearing.step
Geometry source: REAL_STEP
Geometry quality: A
Validated: true
Hash: sha256:4382d87cb411fa890af7f13dc832a58c07652476640f76ef18951ecc9156b5b9
Path kind: shared_cache
Requires model review: false

NOTE: Imported from a STEP model selected by parts_resolver.
      Verify upstream license and dimensional fit before manufacturing.
"""

import cadquery as cq


def make_std_c03() -> cq.Workplane:
    """SLP-C03: KFL001 — imported from STEP file.

    Source: STEP:cache://mechanical/kfl001_flange_bearing.step
    """
    import os
    _here = os.path.dirname(os.path.abspath(__file__))
    _cache_rel = 'mechanical/kfl001_flange_bearing.step'
    _cache_root = os.environ.get("CAD_SPEC_GEN_STEP_CACHE")
    if _cache_root:
        _step_path = os.path.join(os.path.expanduser(_cache_root), _cache_rel)
    else:
        from pathlib import Path
        _step_path = os.path.join(str(Path.home()), ".cad-spec-gen", "step_cache", _cache_rel)
    _step_path = os.path.normpath(_step_path)
    if not os.path.isfile(_step_path):
        raise FileNotFoundError(
            f"STEP file missing for SLP-C03: {_step_path}")
    _model = cq.importers.importStep(_step_path)
    _bbox = _model.val().BoundingBox()
    _origin_shift = (
        -(_bbox.xmin + _bbox.xmax) / 2.0,
        -(_bbox.ymin + _bbox.ymax) / 2.0,
        -_bbox.zmin,
    )
    return _model.translate(_origin_shift)


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_c03()
    p = os.path.join(out, "SLP-C03_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
