"""
M8 电感接近开关 NPN-NO (SLP-F12) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: sensor | Make/Buy: 外购
Material: 
Dimensions: {'d': 8, 'l': 45}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_f12() -> cq.Workplane:
    """SLP-F12: M8 电感接近开关 NPN-NO — simplified sensor geometry."""
    # M8 inductive proximity sensor: threaded barrel with sensing nose
    body = cq.Workplane("XY").circle(4.0).extrude(45)
    for z in (8.100, 12.600, 17.100, 21.600, 26.100):
        thread_groove = (cq.Workplane("XY")
                         .circle(4.030)
                         .circle(3.820)
                         .extrude(0.450)
                         .translate((0, 0, z)))
        body = body.cut(thread_groove)
    nose = cq.Workplane("XY").circle(2.880).extrude(3.000)
    body = body.union(nose)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_f12()
    p = os.path.join(out, "SLP-F12_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
