"""
LM10UU (SLP-C02) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: bearing | Make/Buy: 外购
Material: 
Dimensions: {'od': 19.0, 'id': 10, 'w': 29.0}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_c02() -> cq.Workplane:
    """SLP-C02: LM10UU — simplified bearing geometry."""
    # LM10UU linear bearing: long sleeve with bore and retaining grooves
    body = cq.Workplane("XY").circle(9.5).circle(5.0).extrude(29.0)
    for z in (4.640, 22.160):
        groove = (cq.Workplane("XY")
                  .circle(9.550)
                  .circle(8.780)
                  .extrude(2.200)
                  .translate((0, 0, z)))
        body = body.cut(groove)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_c02()
    p = os.path.join(out, "SLP-C02_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
