"""
KFL001 (SLP-C03) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: bearing | Make/Buy: 外购
Material: 
Dimensions: {'w': 60, 'd': 36, 'h': 16, 'bore_d': 12, 'mount_d': 5.5}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_c03() -> cq.Workplane:
    """SLP-C03: KFL001 — simplified bearing geometry."""
    # KFL001 pillow block bearing: flanged base, raised bearing boss, bore
    body = cq.Workplane("XY").box(60, 36, 5.760, centered=(True, True, False))
    boss = cq.Workplane("XY").circle(12.960).extrude(16)
    body = body.union(boss)
    bore = (cq.Workplane("XY")
            .circle(6.000)
            .extrude(17.000)
            .translate((0, 0, -0.5)))
    body = body.cut(bore)
    for x in (-20.400, 20.400):
        hole = (cq.Workplane("XY")
                .center(x, 0)
                .circle(2.750)
                .extrude(6.360)
                .translate((0, 0, -0.3)))
        body = body.cut(hole)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_c03()
    p = os.path.join(out, "SLP-C03_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
