"""
丝杠 L350 (SLP-P01) — 参数化模板几何

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: transmission | Make/Buy: 自制
Material: —
Source: parametric_transmission:trapezoidal_lead_screw(Tr16x4,L350)
Geometry source: PARAMETRIC_TEMPLATE
Geometry quality: B
Validated: true
Hash: n/a
Path kind: n/a
Requires model review: false

NOTE: Generated from a curated parametric template selected by parts_resolver.
      This is not a vendor STEP model; verify dimensional fit before manufacturing.
"""

import cadquery as cq


def make_std_p01() -> cq.Workplane:
    """SLP-P01: 丝杠 L350 — parametric template geometry."""
    from adapters.parts.parametric_transmission import make_trapezoidal_lead_screw
    return make_trapezoidal_lead_screw(
        outer_diameter_mm=16.0,
        pitch_mm=4.0,
        total_length_mm=350.0,
        thread_length_mm=230.0,
        lower_shaft_diameter_mm=12.0,
        lower_shaft_length_mm=70.0,
        upper_shaft_diameter_mm=12.0,
        upper_shaft_length_mm=40.0,
        root_diameter_mm=13.8,
        starts=1,
    )


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_p01()
    p = os.path.join(out, "SLP-P01_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
