"""
CL57T 闭环驱动器 (SLP-C08) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: other | Make/Buy: 外购
Material: 
Dimensions: {'w': 118, 'd': 75, 'h': 34}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_c08() -> cq.Workplane:
    """SLP-C08: CL57T 闭环驱动器 — simplified other geometry."""
    # CL57T stepper driver: controller case with heat-sink fins
    body = cq.Workplane("XY").box(118, 75, 30.000, centered=(True, True, False))
    for i in range(9):
        x = -40.120 + i * 10.030
        fin = (cq.Workplane("XY")
               .center(x, 0)
               .box(4.130, 61.500, 4.000, centered=(True, True, False))
               .translate((0, 0, 30.000)))
        body = body.union(fin)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_c08()
    p = os.path.join(out, "SLP-C08_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
