"""
CL57T 闭环驱动器 (SLP-C08) — 参数化模板几何

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: other | Make/Buy: 外购
Material: 
Source: jinja_template:cl57t_stepper_driver

NOTE: Generated from a curated parametric template selected by parts_resolver.
      This is not a vendor STEP model; verify dimensional fit before manufacturing.
"""

import cadquery as cq


def make_std_c08() -> cq.Workplane:
    """SLP-C08: CL57T 闭环驱动器 — parametric template geometry."""
    # CL57T stepper driver: controller case with heat-sink fins
    body = cq.Workplane("XY").box(118, 75, 28.000, centered=(True, True, False))
    body = body.edges("|Z").fillet(1.875)
    for i in range(9):
        x = -40.120 + i * 10.030
        fin = (cq.Workplane("XY")
               .center(x, 0)
               .box(4.130, 61.500, 6.000, centered=(True, True, False))
               .translate((0, 0, 28.000)))
        body = body.union(fin)
    terminal = (cq.Workplane("XY")
                .center(36.580, -25.500)
                .box(33.040, 9.000, 4.000, centered=(True, True, False))
                .translate((0, 0, 28.000)))
    dip = (cq.Workplane("XY")
           .center(-38.940, -25.500)
           .box(18.880, 7.500, 3.200, centered=(True, True, False))
           .translate((0, 0, 28.000)))
    label_plate = (cq.Workplane("XY")
                   .center(-23.600, 18.000)
                   .box(49.560, 21.000, 1.080, centered=(True, True, False))
                   .translate((0, 0, 28.480)))
    body = body.union(terminal).union(dip).union(label_plate)
    for x in (-49.560, 49.560):
        for y in (-27.000, 27.000):
            body = body.faces(">Z").workplane().center(x, y).hole(2.625)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_c08()
    p = os.path.join(out, "SLP-C08_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
