"""
NEMA23 闭环步进 ≥1.0Nm (SLP-C07) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: motor | Make/Buy: 外购
Material: 
Dimensions: {'w': 57, 'd': 57, 'h': 80, 'body_h': 56, 'shaft_d': 6.35}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_c07() -> cq.Workplane:
    """SLP-C07: NEMA23 闭环步进 ≥1.0Nm — simplified motor geometry."""
    # NEMA23 stepper motor: square frame, front boss, output shaft
    body = cq.Workplane("XY").box(57, 57, 56, centered=(True, True, False))
    for x in (-28.500, 28.500):
        for y in (-28.500, 28.500):
            relief = (cq.Workplane("XY")
                      .center(x, y)
                      .circle(3.135)
                      .extrude(56.200)
                      .translate((0, 0, -0.1)))
            body = body.cut(relief)
    boss = (cq.Workplane("XY")
            .circle(19.000)
            .extrude(3.000)
            .translate((0, 0, 56)))
    shaft = (cq.Workplane("XY")
             .circle(3.175)
             .extrude(24.000)
             .translate((0, 0, 56)))
    body = body.union(boss).union(shaft)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_c07()
    p = os.path.join(out, "SLP-C07_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
