"""
NEMA23 闭环步进 ≥1.0Nm (SLP-C07) — 真实 STEP 导入件

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: motor | Make/Buy: 外购
Material: 
Source: STEP:std_parts/user_provided/SLP-C07_NEMA23_stepper.step

NOTE: Imported from a STEP model selected by parts_resolver.
      Verify upstream license and dimensional fit before manufacturing.
"""

import cadquery as cq


def make_std_c07() -> cq.Workplane:
    """SLP-C07: NEMA23 闭环步进 ≥1.0Nm — imported from STEP file.

    Source: STEP:std_parts/user_provided/SLP-C07_NEMA23_stepper.step
    """
    import os
    _here = os.path.dirname(os.path.abspath(__file__))
    _step_path = os.path.join(_here, "..", "..", 'std_parts/user_provided/SLP-C07_NEMA23_stepper.step')
    _step_path = os.path.normpath(_step_path)
    if not os.path.isfile(_step_path):
        raise FileNotFoundError(
            f"STEP file missing for SLP-C07: {_step_path}")
    return cq.importers.importStep(_step_path)


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_c07()
    p = os.path.join(out, "SLP-C07_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
