"""
导向轴保护帽 φ10 (SLP-F13) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: other | Make/Buy: 外购
Material: 
Dimensions: {'d': 10, 'l': 8}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_f13() -> cq.Workplane:
    """SLP-F13: 导向轴保护帽 φ10 — simplified other geometry."""
    # guide shaft protective cap: closed cylindrical end cap with shaft pocket
    body = cq.Workplane("XY").circle(5.0).extrude(8)
    pocket = cq.Workplane("XY").circle(3.500).extrude(5.760)
    body = body.cut(pocket)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_f13()
    p = os.path.join(out, "SLP-F13_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
