"""
齿轮泵 (GIS-EE-002-03) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: pump | Make/Buy: 外购
Material: —
Dimensions: {'w': 30, 'd': 25, 'h': 40}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_002_03() -> cq.Workplane:
    """GIS-EE-002-03: 齿轮泵 — simplified pump geometry."""
    # Semi-parametric gear pump: rectangular housing, twin gear cover, port stubs
    body = cq.Workplane("XY").box(30, 25, 36.8, centered=(True, True, False))
    cover = (cq.Workplane("XY")
             .box(26.4, 19.5, 3.2, centered=(True, True, False))
             .translate((0, 0, 36.8)))
    body = body.union(cover)
    for x in (-5.175, 5.175):
        gear_face = (cq.Workplane("XY")
                     .center(x, 0)
                     .circle(4.5)
                     .circle(1.53)
                     .extrude(2.08)
                     .translate((0, 0, 37.92)))
        body = body.union(gear_face)
    for y in (-7.5, 7.5):
        port = (cq.Workplane("YZ")
                .center(y, 20.8)
                .circle(2.5)
                .extrude(6.6)
                .translate((8.4, 0, 0)))
        body = body.union(port)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_002_03()
    p = os.path.join(out, "GIS-EE-002-03_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
