"""
压力阵列 (GIS-EE-003-06) — 真实 STEP 导入件

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: other | Make/Buy: 外购
Material: 4×4薄膜 20×20mm
Source: STEP:cache://sensors/pressure_array_4x4_20mm.step
Geometry source: REAL_STEP
Geometry quality: A
Validated: true
Hash: sha256:863b2f0444f67fa3dc95956ba157f86c3eca4c8801cc1f267b268169995941cc
Path kind: shared_cache
Requires model review: false

NOTE: Imported from a STEP model selected by parts_resolver.
      Verify upstream license and dimensional fit before manufacturing.
"""

import cadquery as cq


def make_std_ee_003_06() -> cq.Workplane:
    """GIS-EE-003-06: 压力阵列 — imported from STEP file.

    Source: STEP:cache://sensors/pressure_array_4x4_20mm.step
    """
    import os
    _here = os.path.dirname(os.path.abspath(__file__))
    _cache_rel = 'sensors/pressure_array_4x4_20mm.step'
    _cache_root = os.environ.get("CAD_SPEC_GEN_STEP_CACHE")
    if _cache_root:
        _step_path = os.path.join(os.path.expanduser(_cache_root), _cache_rel)
    else:
        from pathlib import Path
        _step_path = os.path.join(str(Path.home()), ".cad-spec-gen", "step_cache", _cache_rel)
    _step_path = os.path.normpath(_step_path)
    if not os.path.isfile(_step_path):
        raise FileNotFoundError(
            f"STEP file missing for GIS-EE-003-06: {_step_path}")
    return cq.importers.importStep(_step_path)


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_003_06()
    p = os.path.join(out, "GIS-EE-003-06_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
