"""
M12防水诊断接口 (GIS-EE-006-06) — 真实 STEP 导入件

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: other | Make/Buy: 外购
Material: 4芯
Source: STEP:cache://connectors/m12_4pin_bulkhead.step

NOTE: Imported from a STEP model selected by parts_resolver.
      Verify upstream license and dimensional fit before manufacturing.
"""

import cadquery as cq


def make_std_ee_006_06() -> cq.Workplane:
    """GIS-EE-006-06: M12防水诊断接口 — imported from STEP file.

    Source: STEP:cache://connectors/m12_4pin_bulkhead.step
    """
    import os
    _here = os.path.dirname(os.path.abspath(__file__))
    _cache_rel = 'connectors/m12_4pin_bulkhead.step'
    _cache_root = os.environ.get("CAD_SPEC_GEN_STEP_CACHE")
    if _cache_root:
        _step_path = os.path.join(os.path.expanduser(_cache_root), _cache_rel)
    else:
        from pathlib import Path
        _step_path = os.path.join(str(Path.home()), ".cad-spec-gen", "step_cache", _cache_rel)
    _step_path = os.path.normpath(_step_path)
    if not os.path.isfile(_step_path):
        raise FileNotFoundError(
            f"STEP file missing for GIS-EE-006-06: {_step_path}")
    return cq.importers.importStep(_step_path)


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_006_06()
    p = os.path.join(out, "GIS-EE-006-06_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
