"""
配重块 (GIS-EE-004-10) — 真实 STEP 导入件

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: other | Make/Buy: 外购
Material: 钨合金Φ14×13mm/120g
Source: STEP:cache://weights/tungsten_slug_14x13.step
Geometry source: REAL_STEP
Geometry quality: A
Validated: true
Hash: sha256:6d359bf33559fda31cf84b01fa63cc5ff2bd0c7825aa2ec396674f26d14414bc
Path kind: shared_cache
Requires model review: false

NOTE: Imported from a STEP model selected by parts_resolver.
      Verify upstream license and dimensional fit before manufacturing.
"""

import cadquery as cq


def make_std_ee_004_10() -> cq.Workplane:
    """GIS-EE-004-10: 配重块 — imported from STEP file.

    Source: STEP:cache://weights/tungsten_slug_14x13.step
    """
    import os
    _here = os.path.dirname(os.path.abspath(__file__))
    _cache_rel = 'weights/tungsten_slug_14x13.step'
    _cache_root = os.environ.get("CAD_SPEC_GEN_STEP_CACHE")
    if _cache_root:
        _step_path = os.path.join(os.path.expanduser(_cache_root), _cache_rel)
    else:
        from pathlib import Path
        _step_path = os.path.join(str(Path.home()), ".cad-spec-gen", "step_cache", _cache_rel)
    _step_path = os.path.normpath(_step_path)
    if not os.path.isfile(_step_path):
        raise FileNotFoundError(
            f"STEP file missing for GIS-EE-004-10: {_step_path}")
    return cq.importers.importStep(_step_path)


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_004_10()
    p = os.path.join(out, "GIS-EE-004-10_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
