"""
定位销 (GIS-EE-001-12) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: locating | Make/Buy: 外购
Material: Φ3×6mm H7/g6
Source: sw_toolbox:GB/pins and keys/pins with split pin hole gb.sldprt

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_001_12() -> cq.Workplane:
    """GIS-EE-001-12: 定位销 — imported from STEP file.

    Source: sw_toolbox:GB/pins and keys/pins with split pin hole gb.sldprt
    """
    import os
    _here = os.path.dirname(os.path.abspath(__file__))
    _step_path = 'C:\\Users\\procheng\\.cad-spec-gen\\step_cache\\sw_toolbox\\GB\\pins and keys\\pins with split pin hole gb.step'
    _step_path = os.path.normpath(_step_path)
    if not os.path.isfile(_step_path):
        raise FileNotFoundError(
            f"STEP file missing for GIS-EE-001-12: {_step_path}")
    return cq.importers.importStep(_step_path)


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_001_12()
    p = os.path.join(out, "GIS-EE-001-12_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
