"""
微量泵 (GIS-EE-004-09) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: pump | Make/Buy: 外购
Material: 电磁阀式
Dimensions: {'w': 20, 'h': 15, 'l': 30}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_004_09() -> cq.Workplane:
    """GIS-EE-004-09: 微量泵 — simplified pump geometry."""
    # Simplified pump: box with port stubs
    body = cq.Workplane("XY").box(20, 15, 30, centered=(True, True, False))
    # Input/output port stubs
    body = body.faces(">X").workplane().center(0, 15.0).circle(3).extrude(5)
    body = body.faces("<X").workplane().center(0, 15.0).circle(3).extrude(5)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_004_09()
    p = os.path.join(out, "GIS-EE-004-09_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
