"""
压力阵列 (GIS-EE-003-06) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: other | Make/Buy: 外购
Material: 4×4薄膜 20×20mm
Dimensions: {'w': 20.0, 'l': 20.0, 'h': 0.6}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_003_06() -> cq.Workplane:
    """GIS-EE-003-06: 压力阵列 — simplified other geometry."""
    # Semi-parametric pressure array: thin film carrier, 4x4 sensing pads, flex tail
    body = cq.Workplane("XY").box(20.0, 20.0, 0.6, centered=(True, True, False))
    for r in range(4):
        for c in range(4):
            x = (c - (4 - 1) / 2.0) * 4.0
            y = (r - (4 - 1) / 2.0) * 4.0
            pad = (cq.Workplane("XY")
                   .center(x, y)
                   .box(2.7777777777777777, 2.7777777777777777, 0.21, centered=(True, True, False))
                   .translate((0, 0, 0.62)))
            body = body.union(pad)
    tail = (cq.Workplane("XY")
            .center(0, -14.399999999999999)
            .box(6.4, 8.4, 0.6, centered=(True, True, False)))
    body = body.union(tail)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_003_06()
    p = os.path.join(out, "GIS-EE-003-06_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
