"""
齿轮减速组（电机→收带卷轴） (GIS-EE-004-04) — 真实 STEP 导入件

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: reducer | Make/Buy: 外购
Material: 塑料齿轮
Source: STEP:cache://transmission/gear_train_reducer_25x25x35.step
Geometry source: REAL_STEP
Geometry quality: A
Validated: true
Hash: sha256:ea1cbc0f224ef8b10a2d9fdbbdb4b9a2d116fb2402e733d84533216a65612e29
Path kind: shared_cache
Requires model review: false

NOTE: Imported from a STEP model selected by parts_resolver.
      Verify upstream license and dimensional fit before manufacturing.
"""

import cadquery as cq


def make_std_ee_004_04() -> cq.Workplane:
    """GIS-EE-004-04: 齿轮减速组（电机→收带卷轴） — imported from STEP file.

    Source: STEP:cache://transmission/gear_train_reducer_25x25x35.step
    """
    import os
    _here = os.path.dirname(os.path.abspath(__file__))
    _cache_rel = 'transmission/gear_train_reducer_25x25x35.step'
    _cache_root = os.environ.get("CAD_SPEC_GEN_STEP_CACHE")
    if _cache_root:
        _step_path = os.path.join(os.path.expanduser(_cache_root), _cache_rel)
    else:
        from pathlib import Path
        _step_path = os.path.join(str(Path.home()), ".cad-spec-gen", "step_cache", _cache_rel)
    _step_path = os.path.normpath(_step_path)
    if not os.path.isfile(_step_path):
        raise FileNotFoundError(
            f"STEP file missing for GIS-EE-004-04: {_step_path}")
    return cq.importers.importStep(_step_path)


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_004_04()
    p = os.path.join(out, "GIS-EE-004-04_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
