"""
M12防水诊断接口 (GIS-EE-006-06) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: other | Make/Buy: 外购
Material: 4芯
Dimensions: {'d': 12, 'l': 18}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_006_06() -> cq.Workplane:
    """GIS-EE-006-06: M12防水诊断接口 — simplified other geometry."""
    # Semi-parametric M12 connector: threaded shell, flange, coded pin face
    shell = cq.Workplane("XY").circle(6.0).extrude(18)
    flange = cq.Workplane("XY").polygon(6, 16.200000000000003).extrude(2.64).translate((0, 0, 6.12))
    cable_gland = cq.Workplane("XY").circle(4.5600000000000005).extrude(6.84).translate((0, 0, 18))
    body = shell.union(flange).union(cable_gland)
    for i in range(4):
        angle = 6.283185307179586 * i / 4
        x = 3.3600000000000003 * __import__("math").cos(angle)
        y = 3.3600000000000003 * __import__("math").sin(angle)
        pin = (cq.Workplane("XY")
               .center(x, y)
               .circle(0.42000000000000004)
               .extrude(0.96)
               .translate((0, 0, 24.84)))
        body = body.union(pin)
    key = (cq.Workplane("XY")
           .center(0, -3.3600000000000003)
           .box(1.92, 4.32, 0.96, centered=(True, True, False))
           .translate((0, 0, 24.84)))
    body = body.union(key)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_006_06()
    p = os.path.join(out, "GIS-EE-006-06_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
