"""
行星减速器 (GIS-EE-001-06) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: reducer | Make/Buy: 外购
Material: Maxon GP22C (53:1)
Dimensions: {'d': 22, 'l': 35, 'shaft_d': 6, 'shaft_l': 10}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_001_06() -> cq.Workplane:
    """GIS-EE-001-06: 行星减速器 — simplified reducer geometry."""
    # Simplified reducer/gearbox: cylinder + output shaft
    body = cq.Workplane("XY").circle(11.0).extrude(35)
    body = body.faces(">Z").workplane().circle(3.0).extrude(10)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_001_06()
    p = os.path.join(out, "GIS-EE-001-06_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
