"""
光电编码器（带面余量） (GIS-EE-004-07) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: sensor | Make/Buy: 外购
Material: 反射式
Dimensions: {'w': 15.0, 'd': 15.0, 'h': 12.0}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_004_07() -> cq.Workplane:
    """GIS-EE-004-07: 光电编码器（带面余量） — simplified sensor geometry."""
    # Semi-parametric photoelectric encoder: sensor body, optical window, mounting ears
    body = cq.Workplane("XY").box(10.799999999999999, 9.3, 6.24, centered=(True, True, False))
    face = (cq.Workplane("XY")
            .center(0, 2.1)
            .box(6.3, 2.6999999999999997, 1.6800000000000002, centered=(True, True, False))
            .translate((0, 0, 6.24)))
    body = body.union(face)
    for x in (-1.65, 1.65):
        lens = (cq.Workplane("XY")
                .center(x, 2.1)
                .circle(0.825)
                .extrude(0.96)
                .translate((0, 0, 7.92)))
        body = body.union(lens)
    for x in (-6.3, 6.3):
        ear = (cq.Workplane("XY")
               .center(x, 0)
               .box(2.1, 6.9, 2.2464, centered=(True, True, False)))
        body = body.union(ear)
    cable = (cq.Workplane("XY")
             .center(0, -5.7)
             .box(5.1000000000000005, 2.4, 3.3600000000000003, centered=(True, True, False)))
    body = body.union(cable)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_004_07()
    p = os.path.join(out, "GIS-EE-004-07_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
