"""
配重块 (GIS-EE-003-07) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: other | Make/Buy: 外购
Material: 钨合金Φ12×7mm/50g
Dimensions: {'d': 12.0, 'l': 7.0}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_003_07() -> cq.Workplane:
    """GIS-EE-003-07: 配重块 — simplified other geometry."""
    # Generic cylindrical block
    body = cq.Workplane("XY").circle(6.0).extrude(7.0)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_003_07()
    p = os.path.join(out, "GIS-EE-003-07_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
