"""
恒力弹簧（供带侧张力） (GIS-EE-004-06) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: spring | Make/Buy: 外购
Material: SUS301, 0.3N
Dimensions: {'od': 10, 'id': 5, 't': 0.7, 'h': 0.85}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_004_06() -> cq.Workplane:
    """GIS-EE-004-06: 恒力弹簧（供带侧张力） — simplified spring geometry."""
    # Simplified disc spring: annular ring (stack approximation)
    body = (cq.Workplane("XY")
            .circle(5.0).circle(2.5).extrude(0.85)
            )
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_004_06()
    p = os.path.join(out, "GIS-EE-004-06_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
