"""
阻尼垫 (GIS-EE-003-05) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: other | Make/Buy: 外购
Material: 黏弹性硅橡胶
Dimensions: {'d': 15, 'l': 10}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_003_05() -> cq.Workplane:
    """GIS-EE-003-05: 阻尼垫 — simplified other geometry."""
    # Generic cylindrical block
    body = cq.Workplane("XY").circle(7.5).extrude(10)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_003_05()
    p = os.path.join(out, "GIS-EE-003-05_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
