"""
AE传感器 (GIS-EE-003-01) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: sensor | Make/Buy: 外购
Material: TWAE-03
Dimensions: {'d': 8, 'l': 10}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_003_01() -> cq.Workplane:
    """GIS-EE-003-01: AE传感器 — simplified sensor geometry."""
    # Simplified sensor: cylinder
    body = cq.Workplane("XY").circle(4.0).extrude(10)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_003_01()
    p = os.path.join(out, "GIS-EE-003-01_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
