"""
微量泵（溶剂喷射） (GIS-EE-004-09) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: pump | Make/Buy: 外购
Material: 电磁阀式
Dimensions: {'w': 20, 'd': 15, 'h': 30}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_004_09() -> cq.Workplane:
    """GIS-EE-004-09: 微量泵（溶剂喷射） — simplified pump geometry."""
    # Semi-parametric micro dosing pump: solenoid block, valve coil, nozzle pair
    body = cq.Workplane("XY").box(20, 15, 30, centered=(True, True, False))
    coil = (cq.Workplane("XZ")
            .center(0, 17.4)
            .circle(4.125)
            .extrude(5.8500000000000005, both=True))
    body = body.union(coil)
    for x in (-4.8, 4.8):
        nozzle = (cq.Workplane("YZ")
                  .center(-6.3, 5.3999999999999995)
                  .circle(1.2)
                  .extrude(3.2, both=True)
                  .translate((x, 0, 0)))
        body = body.union(nozzle)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_004_09()
    p = os.path.join(out, "GIS-EE-004-09_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
