"""
阻尼垫 (GIS-EE-003-05) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: other | Make/Buy: 外购
Material: 黏弹性硅橡胶
Dimensions: {'d': 20.0, 'l': 20.0}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_003_05() -> cq.Workplane:
    """GIS-EE-003-05: 阻尼垫 — simplified other geometry."""
    # Semi-parametric viscoelastic damping pad: rubber puck with concentric damping ribs
    body = cq.Workplane("XY").circle(10.0).extrude(20.0)
    for r in (4.0, 6.6000000000000005):
        rib = (cq.Workplane("XY")
               .circle(r)
               .circle(max(r - 0.8999999999999999, 0.1))
               .extrude(0.8)
               .translate((0, 0, 19.2)))
        body = body.union(rib)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_003_05()
    p = os.path.join(out, "GIS-EE-003-05_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
