"""
ZIF连接器 (GIS-EE-001-10) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: connector | Make/Buy: 外购
Material: Molex 5052xx
Dimensions: {'w': 12, 'h': 3, 'l': 8}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_001_10() -> cq.Workplane:
    """GIS-EE-001-10: ZIF连接器 — simplified connector geometry."""
    # Simplified flat connector
    body = cq.Workplane("XY").box(12, 8, 3, centered=(True, True, False))
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_001_10()
    p = os.path.join(out, "GIS-EE-001-10_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
