"""
信号调理PCB (GIS-EE-006-02) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: other | Make/Buy: 外购
Material: 定制4层混合信号
Dimensions: {'w': 45, 'l': 35, 'h': 1.6}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_006_02() -> cq.Workplane:
    """GIS-EE-006-02: 信号调理PCB — simplified other geometry."""
    # Semi-parametric PCB assembly: board, corner holes, ICs, connector pads
    body = cq.Workplane("XY").box(45, 35, 1.6, centered=(True, True, False))
    for x in (-18.9, 18.9):
        for y in (-13.3, 13.3):
            body = body.faces(">Z").workplane().center(x, y).hole(2.8000000000000003)
    main_ic = (cq.Workplane("XY")
               .center(-7.2, 0)
               .box(11.700000000000001, 7.7, 1.04, centered=(True, True, False))
               .translate((0, 0, 1.6)))
    aux_ic = (cq.Workplane("XY")
              .center(9.9, 4.2)
              .box(8.1, 5.6000000000000005, 0.7200000000000001, centered=(True, True, False))
              .translate((0, 0, 1.6)))
    body = body.union(main_ic).union(aux_ic)
    for i in range(8):
        x = (i - 3.5) * 3.1500000000000004
        pad = (cq.Workplane("XY")
               .center(x, -14.7)
               .box(1.5750000000000002, 2.8000000000000003, 0.192, centered=(True, True, False))
               .translate((0, 0, 1.62)))
        body = body.union(pad)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_006_02()
    p = os.path.join(out, "GIS-EE-006-02_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
