"""
FFC线束总成 (GIS-EE-001-09) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: connector | Make/Buy: 外购
Material: Molex 15168, 20芯×500mm
Dimensions: {'w': 12, 'l': 50, 'h': 1}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_001_09() -> cq.Workplane:
    """GIS-EE-001-09: FFC线束总成 — simplified connector geometry."""
    # Semi-parametric FFC ribbon: thin cable, end stiffeners, exposed contacts
    ribbon = cq.Workplane("XY").box(12, 50, 1, centered=(True, True, False))
    body = ribbon
    for y in (-23.0, 23.0):
        stiffener = (cq.Workplane("XY")
                     .center(0, y)
                     .box(13.6, 4.0, 1.6, centered=(True, True, False)))
        body = body.union(stiffener)
        for i in range(20):
            x = (i - (20 - 1) / 2.0) * 0.5714285714285714
            pad = (cq.Workplane("XY")
                   .center(x, y)
                   .box(0.2571428571428571, 2.88, 0.22, centered=(True, True, False))
                   .translate((0, 0, 1.62)))
            body = body.union(pad)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_001_09()
    p = os.path.join(out, "GIS-EE-001-09_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
