"""
弹簧销组件（含弹簧） (GIS-EE-001-07) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: spring | Make/Buy: 外购
Material: Φ4×20mm锥形头
Dimensions: {'d': 4.0, 'l': 20.0}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_001_07() -> cq.Workplane:
    """GIS-EE-001-07: 弹簧销组件（含弹簧） — simplified spring geometry."""
    # Simplified disc spring: annular ring (stack approximation)
    body = (cq.Workplane("XY")
            .circle(5.0).circle(2.5).extrude(0.85)
            )
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_001_07()
    p = os.path.join(out, "GIS-EE-001-07_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
