"""
微型电机 (GIS-EE-004-03) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: motor | Make/Buy: 外购
Material: DC 3V Φ16mm
Dimensions: {'d': 16.0, 'l': 30.0}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_004_03() -> cq.Workplane:
    """GIS-EE-004-03: 微型电机 — simplified motor geometry."""
    # Semi-parametric mini DC motor: can, end caps, recessed shaft, rear terminals
    can = cq.Workplane("XY").circle(8.0).extrude(24.900000000000002).translate((0, 0, 2.4))
    rear = cq.Workplane("XY").circle(7.36).extrude(2.4)
    front = cq.Workplane("XY").circle(7.52).extrude(2.6999999999999997).translate((0, 0, 27.3))
    shaft = cq.Workplane("XY").circle(1.0).extrude(5.3999999999999995).translate((0, 0, 24.6))
    body = can.union(rear).union(front).union(shaft)
    for y in (-2.88, 2.88):
        tab = (cq.Workplane("XY")
               .center(4.8, y)
               .box(1.6, 2.88, 0.84, centered=(True, True, False))
               .translate((0, 0, 0.48)))
        body = body.union(tab)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_004_03()
    p = os.path.join(out, "GIS-EE-004-03_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
