"""
齿轮泵 (GIS-EE-002-03) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: pump | Make/Buy: 外购
Material: —
Dimensions: {'w': 30, 'h': 25, 'l': 40}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_002_03() -> cq.Workplane:
    """GIS-EE-002-03: 齿轮泵 — simplified pump geometry."""
    # Simplified pump: box with port stubs
    body = cq.Workplane("XY").box(30, 25, 40, centered=(True, True, False))
    # Input/output port stubs
    body = body.faces(">X").workplane().center(0, 20.0).circle(3).extrude(5)
    body = body.faces("<X").workplane().center(0, 20.0).circle(3).extrude(5)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_002_03()
    p = os.path.join(out, "GIS-EE-002-03_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
