"""
微量泵（溶剂喷射） (GIS-EE-004-09) — 真实 STEP 导入件

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: pump | Make/Buy: 外购
Material: 电磁阀式
Source: STEP:cache://process/micro_dosing_pump_20x15x30.step
Geometry source: REAL_STEP
Geometry quality: A
Validated: true
Hash: sha256:1d15f1f9db0adbf91a0eb02834f840de0d4bb37fdaa42e2a35509ec94d600b72
Path kind: shared_cache
Requires model review: false

NOTE: Imported from a STEP model selected by parts_resolver.
      Verify upstream license and dimensional fit before manufacturing.
"""

import cadquery as cq


def make_std_ee_004_09() -> cq.Workplane:
    """GIS-EE-004-09: 微量泵（溶剂喷射） — imported from STEP file.

    Source: STEP:cache://process/micro_dosing_pump_20x15x30.step
    """
    import os
    _here = os.path.dirname(os.path.abspath(__file__))
    _cache_rel = 'process/micro_dosing_pump_20x15x30.step'
    _cache_root = os.environ.get("CAD_SPEC_GEN_STEP_CACHE")
    if _cache_root:
        _step_path = os.path.join(os.path.expanduser(_cache_root), _cache_rel)
    else:
        from pathlib import Path
        _step_path = os.path.join(str(Path.home()), ".cad-spec-gen", "step_cache", _cache_rel)
    _step_path = os.path.normpath(_step_path)
    if not os.path.isfile(_step_path):
        raise FileNotFoundError(
            f"STEP file missing for GIS-EE-004-09: {_step_path}")
    return cq.importers.importStep(_step_path)


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_004_09()
    p = os.path.join(out, "GIS-EE-004-09_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
