"""
碟形弹簧垫圈 (GIS-EE-001-04) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: spring | Make/Buy: 外购
Material: DIN 2093 A6
Dimensions: {'od': 12.5, 'id': 6.2, 't': 0.7, 'h': 0.85}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_001_04() -> cq.Workplane:
    """GIS-EE-001-04: 碟形弹簧垫圈 — simplified spring geometry."""
    # Simplified disc spring: annular ring (stack approximation)
    body = (cq.Workplane("XY")
            .circle(6.25).circle(3.1).extrude(0.85)
            )
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_001_04()
    p = os.path.join(out, "GIS-EE-001-04_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
