"""
O型圈 (GIS-EE-001-03) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: seal | Make/Buy: 外购
Material: FKM Φ80×2.4
Dimensions: {'d': 80.0, 'l': 2.4}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_001_03() -> cq.Workplane:
    """GIS-EE-001-03: O型圈 — simplified seal geometry."""
    # Simplified O-ring: torus
    path = cq.Workplane("XY").circle(38.8)
    body = (cq.Workplane("XZ")
            .center(38.8, 0)
            .circle(1.2)
            .sweep(path))
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_001_03()
    p = os.path.join(out, "GIS-EE-001-03_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
