"""
I300-UHF-GT传感器 (GIS-EE-005-01) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: sensor | Make/Buy: 外购
Material: 波译科技
Dimensions: {'d': 45, 'l': 60}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_005_01() -> cq.Workplane:
    """GIS-EE-005-01: I300-UHF-GT传感器 — simplified sensor geometry."""
    # Semi-parametric UHF sensor: cylindrical body, antenna face, cable exit
    body = cq.Workplane("XY").circle(22.5).extrude(60)
    face = cq.Workplane("XY").circle(19.35).extrude(1.8).translate((0, 0, 60))
    antenna = (cq.Workplane("XY")
               .box(26.099999999999998, 7.2, 1.8, centered=(True, True, False))
               .translate((0, 0, 61.8)))
    cable = (cq.Workplane("YZ")
             .circle(2.025)
             .extrude(18.9)
             .translate((22.5, 0, 34.8)))
    body = body.union(face).union(antenna).union(cable)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_005_01()
    p = os.path.join(out, "GIS-EE-005-01_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
