"""
弹性衬垫 (GIS-EE-004-05) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: other | Make/Buy: 外购
Material: 硅橡胶Shore A 30, 20×15×5mm
Dimensions: {'w': 20.0, 'd': 15.0, 'h': 5.0}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_004_05() -> cq.Workplane:
    """GIS-EE-004-05: 弹性衬垫 — simplified other geometry."""
    # Semi-parametric elastomer cushion pad: soft rectangular pad with raised ribs
    body = cq.Workplane("XY").box(20.0, 15.0, 3.1, centered=(True, True, False))
    for x in (-4.8, 0, 4.8):
        rib = (cq.Workplane("XY")
               .center(x, 0)
               .box(3.2, 12.299999999999999, 1.9, centered=(True, True, False))
               .translate((0, 0, 3.1)))
        body = body.union(rib)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_004_05()
    p = os.path.join(out, "GIS-EE-004-05_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
