"""
六轴力传感器 (GIS-EE-003-02) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: sensor | Make/Buy: 外购
Material: ATI Nano17/坤维KWR42
Dimensions: {'d': 17, 'l': 14.5}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_003_02() -> cq.Workplane:
    """GIS-EE-003-02: 六轴力传感器 — simplified sensor geometry."""
    # Simplified sensor: cylinder
    body = cq.Workplane("XY").circle(8.5).extrude(14.5)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_003_02()
    p = os.path.join(out, "GIS-EE-003-02_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
