"""
清洁带盒（供带卷轴+收带卷轴+10m无纺布带） (GIS-EE-004-02) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: other | Make/Buy: 外购
Material: 超细纤维无纺布
Dimensions: {'w': 42, 'd': 28, 'h': 12}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_004_02() -> cq.Workplane:
    """GIS-EE-004-02: 清洁带盒（供带卷轴+收带卷轴+10m无纺布带） — simplified other geometry."""
    # Semi-parametric cleaning tape cassette: cassette body, supply/take-up reels, tape path
    body = cq.Workplane("XY").box(42, 28, 5.04, centered=(True, True, False))
    for x in (-9.66, 9.66):
        reel = (cq.Workplane("XY")
                .center(x, 0)
                .circle(5.04)
                .circle(1.9152)
                .extrude(6.96)
                .translate((0, 0, 5.04)))
        hub = (cq.Workplane("XY")
               .center(x, 0)
               .circle(1.008)
               .extrude(12)
               .translate((0, 0, 0)))
        body = body.union(reel).union(hub)
    tape_span = (cq.Workplane("XY")
                 .box(26.04, 1.9600000000000002, 0.96, centered=(True, True, False))
                 .translate((0, 0, 8.3808)))
    window = (cq.Workplane("XY")
              .center(0, -9.24)
              .box(17.64, 4.48, 2.4000000000000004, centered=(True, True, False))
              .translate((0, 0, 5.04)))
    body = body.union(tape_span).union(window)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_004_02()
    p = os.path.join(out, "GIS-EE-004-02_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
