"""
溶剂储罐 (GIS-EE-004-08) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: tank | Make/Buy: 外购
Material: Φ25×110mm
Dimensions: {'d': 25.0, 'l': 110.0}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_004_08() -> cq.Workplane:
    """GIS-EE-004-08: 溶剂储罐 — simplified tank geometry."""
    # Simplified tank: cylinder with domed ends
    body = cq.Workplane("XY").circle(12.5).extrude(110.0)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_004_08()
    p = os.path.join(out, "GIS-EE-004-08_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
