"""
刮涂头 (GIS-EE-002-04) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: other | Make/Buy: 外购
Material: 硅橡胶
Dimensions: {'w': 15, 'd': 8, 'h': 6}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_002_04() -> cq.Workplane:
    """GIS-EE-002-04: 刮涂头 — simplified other geometry."""
    # Semi-parametric scraper head: clamp bar, compliant blade, mounting holes
    clamp = cq.Workplane("XY").box(15, 8, 2.7, centered=(True, True, False))
    blade = (cq.Workplane("XY")
             .center(0, -1.6)
             .box(13.8, 3.36, 3.3000000000000003, centered=(True, True, False))
             .translate((0, 0, 2.0999999999999996)))
    body = clamp.union(blade)
    for x in (-4.5, 4.5):
        body = body.faces(">Z").workplane().center(x, 0).hole(1.5)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_002_04()
    p = os.path.join(out, "GIS-EE-002-04_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
