"""
齿轮减速组（电机→收带卷轴） (GIS-EE-004-04) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: reducer | Make/Buy: 外购
Material: 塑料齿轮
Dimensions: {'w': 25.0, 'd': 25.0, 'h': 35.0, 'shaft_d': 6}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_004_04() -> cq.Workplane:
    """GIS-EE-004-04: 齿轮减速组（电机→收带卷轴） — simplified reducer geometry."""
    # Semi-parametric gear train reducer: gearbox case, visible gear pair, output boss
    body = cq.Workplane("XY").box(21.5, 18.0, 24.5, centered=(True, True, False))
    cover = (cq.Workplane("XY")
             .box(19.5, 16.0, 3.5, centered=(True, True, False))
             .translate((0, 0, 24.5)))
    body = body.union(cover)
    for x in (-4.48, 4.48):
        gear = (cq.Workplane("XY")
                .center(x, 0)
                .circle(4.0)
                .circle(1.36)
                .extrude(2.275)
                .translate((0, 0, 25.725)))
        body = body.union(gear)
    boss_z = 35.0 - 4.199999999999999 - 2.8000000000000003
    boss = cq.Workplane("XY").circle(4.5).extrude(2.8000000000000003).translate((0, 0, boss_z))
    shaft = cq.Workplane("XY").circle(3.0).extrude(4.199999999999999).translate((0, 0, 30.8))
    body = body.union(boss).union(shaft)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_004_04()
    p = os.path.join(out, "GIS-EE-004-04_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
