"""
微型轴承 (GIS-EE-004-11) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: bearing | Make/Buy: 外购
Material: MR105ZZ（Φ10×Φ5×4mm）
Dimensions: {'od': 10, 'id': 5, 'w': 4}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_004_11() -> cq.Workplane:
    """GIS-EE-004-11: 微型轴承 — simplified bearing geometry."""
    # Simplified bearing: outer ring + inner ring + gap
    outer = cq.Workplane("XY").circle(5.0).circle(4.0).extrude(4)
    inner = cq.Workplane("XY").circle(3.5).circle(2.5).extrude(4)
    body = outer.union(inner)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_004_11()
    p = os.path.join(out, "GIS-EE-004-11_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
