"""
光电编码器（带面余量） (GIS-EE-004-07) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: sensor | Make/Buy: 外购
Material: 反射式
Dimensions: {'d': 15, 'l': 12}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_004_07() -> cq.Workplane:
    """GIS-EE-004-07: 光电编码器（带面余量） — simplified sensor geometry."""
    # Simplified sensor: cylinder
    body = cq.Workplane("XY").circle(7.5).extrude(12)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_004_07()
    p = os.path.join(out, "GIS-EE-004-07_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
