"""
刮涂头 (GIS-EE-002-04) — 真实 STEP 导入件

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: other | Make/Buy: 外购
Material: 硅橡胶
Source: STEP:cache://process/scraper_head_20x10x8.step
Geometry source: REAL_STEP
Geometry quality: A
Validated: true
Hash: sha256:22c5e9185edf266a1ecb217109c16e3ebd3bb751bb36a51ea7adfafcb8f4995e
Path kind: shared_cache
Requires model review: false

NOTE: Imported from a STEP model selected by parts_resolver.
      Verify upstream license and dimensional fit before manufacturing.
"""

import cadquery as cq


def make_std_ee_002_04() -> cq.Workplane:
    """GIS-EE-002-04: 刮涂头 — imported from STEP file.

    Source: STEP:cache://process/scraper_head_20x10x8.step
    """
    import os
    _here = os.path.dirname(os.path.abspath(__file__))
    _cache_rel = 'process/scraper_head_20x10x8.step'
    _cache_root = os.environ.get("CAD_SPEC_GEN_STEP_CACHE")
    if _cache_root:
        _step_path = os.path.join(os.path.expanduser(_cache_root), _cache_rel)
    else:
        from pathlib import Path
        _step_path = os.path.join(str(Path.home()), ".cad-spec-gen", "step_cache", _cache_rel)
    _step_path = os.path.normpath(_step_path)
    if not os.path.isfile(_step_path):
        raise FileNotFoundError(
            f"STEP file missing for GIS-EE-002-04: {_step_path}")
    return cq.importers.importStep(_step_path)


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_002_04()
    p = os.path.join(out, "GIS-EE-002-04_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
