"""
储罐 (GIS-EE-002-02) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: tank | Make/Buy: 外购
Material: 不锈钢Φ38×280mm
Dimensions: {'d': 38.0, 'l': 280.0}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_002_02() -> cq.Workplane:
    """GIS-EE-002-02: 储罐 — simplified tank geometry."""
    # Semi-parametric fluid reservoir: cylinder, end caps, clamp bands, fill boss
    body = cq.Workplane("XY").circle(19.0).extrude(280.0)
    for z in (8.0, 266.4):
        band = (cq.Workplane("XY")
                .circle(19.0)
                .circle(17.9)
                .extrude(5.6000000000000005)
                .translate((0, 0, z)))
        body = body.union(band)
    front = cq.Workplane("XY").circle(16.34).extrude(8.0)
    rear = cq.Workplane("XY").circle(16.34).extrude(8.0).translate((0, 0, 272.0))
    fill_boss = (cq.Workplane("XY")
                 .center(0, 8.36)
                 .circle(4.56)
                 .extrude(4.56)
                 .translate((0, 0, 154.0)))
    body = body.union(front).union(rear).union(fill_boss)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_002_02()
    p = os.path.join(out, "GIS-EE-002-02_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
