"""
FFC线束总成 (GIS-EE-001-09) — 真实 STEP 导入件

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: connector | Make/Buy: 外购
Material: Molex 15168, 20芯×500mm
Source: STEP:cache://molex/15168_ffc_20p.step
Geometry source: REAL_STEP
Geometry quality: A
Validated: true
Hash: sha256:d6b016989e4e9bccdae7a3a3d238f81ba8503a722eb5e188fc2eaa79ba96b6a5
Path kind: shared_cache
Requires model review: false

NOTE: Imported from a STEP model selected by parts_resolver.
      Verify upstream license and dimensional fit before manufacturing.
"""

import cadquery as cq


def make_std_ee_001_09() -> cq.Workplane:
    """GIS-EE-001-09: FFC线束总成 — imported from STEP file.

    Source: STEP:cache://molex/15168_ffc_20p.step
    """
    import os
    _here = os.path.dirname(os.path.abspath(__file__))
    _cache_rel = 'molex/15168_ffc_20p.step'
    _cache_root = os.environ.get("CAD_SPEC_GEN_STEP_CACHE")
    if _cache_root:
        _step_path = os.path.join(os.path.expanduser(_cache_root), _cache_rel)
    else:
        from pathlib import Path
        _step_path = os.path.join(str(Path.home()), ".cad-spec-gen", "step_cache", _cache_rel)
    _step_path = os.path.normpath(_step_path)
    if not os.path.isfile(_step_path):
        raise FileNotFoundError(
            f"STEP file missing for GIS-EE-001-09: {_step_path}")
    return cq.importers.importStep(_step_path)


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_001_09()
    p = os.path.join(out, "GIS-EE-001-09_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
