"""
弹簧销组件（含弹簧） (GIS-EE-001-07) — 真实 STEP 导入件

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: spring | Make/Buy: 外购
Material: Φ4×20mm锥形头
Source: STEP:cache://mechanical/spring_pin_4x20.step

NOTE: Imported from a STEP model selected by parts_resolver.
      Verify upstream license and dimensional fit before manufacturing.
"""

import cadquery as cq


def make_std_ee_001_07() -> cq.Workplane:
    """GIS-EE-001-07: 弹簧销组件（含弹簧） — imported from STEP file.

    Source: STEP:cache://mechanical/spring_pin_4x20.step
    """
    import os
    _here = os.path.dirname(os.path.abspath(__file__))
    _cache_rel = 'mechanical/spring_pin_4x20.step'
    _cache_root = os.environ.get("CAD_SPEC_GEN_STEP_CACHE")
    if _cache_root:
        _step_path = os.path.join(os.path.expanduser(_cache_root), _cache_rel)
    else:
        from pathlib import Path
        _step_path = os.path.join(str(Path.home()), ".cad-spec-gen", "step_cache", _cache_rel)
    _step_path = os.path.normpath(_step_path)
    if not os.path.isfile(_step_path):
        raise FileNotFoundError(
            f"STEP file missing for GIS-EE-001-07: {_step_path}")
    return cq.importers.importStep(_step_path)


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_001_07()
    p = os.path.join(out, "GIS-EE-001-07_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
