"""
齿轮减速组（电机→收带卷轴） (GIS-EE-004-04) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: reducer | Make/Buy: 外购
Material: 塑料齿轮
Dimensions: {'d': 25, 'l': 35, 'shaft_d': 6, 'shaft_l': 10}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_004_04() -> cq.Workplane:
    """GIS-EE-004-04: 齿轮减速组（电机→收带卷轴） — simplified reducer geometry."""
    # Simplified reducer/gearbox: cylinder + output shaft
    body = cq.Workplane("XY").circle(12.5).extrude(35)
    body = body.faces(">Z").workplane().circle(3.0).extrude(10)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_004_04()
    p = os.path.join(out, "GIS-EE-004-04_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
