"""
SMA穿壁连接器 (GIS-EE-006-05) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: connector | Make/Buy: 外购
Material: 50Ω
Dimensions: {'d': 6.5, 'l': 15}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_006_05() -> cq.Workplane:
    """GIS-EE-006-05: SMA穿壁连接器 — simplified connector geometry."""
    # Semi-parametric SMA bulkhead connector: coax barrel, hex nut, center pin
    barrel = cq.Workplane("XY").circle(3.25).extrude(15)
    hex_nut = cq.Workplane("XY").polygon(6, 10.725).extrude(2.47).translate((0, 0, 6.3))
    rear_thread = cq.Workplane("XY").circle(2.47).extrude(4.2).translate((0, 0, 15))
    center_pin = cq.Workplane("XY").circle(0.52).extrude(2.6999999999999997).translate((0, 0, -2.6999999999999997))
    body = barrel.union(hex_nut).union(rear_thread).union(center_pin)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_006_05()
    p = os.path.join(out, "GIS-EE-006-05_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
