"""
微型电机 (GIS-EE-004-03) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: motor | Make/Buy: 外购
Material: DC 3V Φ16mm
Dimensions: {'d': 16, 'l': 30, 'shaft_d': 2, 'shaft_l': 8}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_004_03() -> cq.Workplane:
    """GIS-EE-004-03: 微型电机 — simplified motor geometry."""
    # Simplified motor: cylinder + shaft
    body = cq.Workplane("XY").circle(8.0).extrude(30)
    # Output shaft
    body = body.faces(">Z").workplane().circle(1.0).extrude(8)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_004_03()
    p = os.path.join(out, "GIS-EE-004-03_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
