"""
AE传感器 (GIS-EE-003-01) — 真实 STEP 导入件

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: sensor | Make/Buy: 外购
Material: TWAE-03
Source: STEP:cache://ati/nano17.step
Geometry source: REAL_STEP
Geometry quality: A
Validated: true
Hash: sha256:aaa5d3b1c4c86a60fccbbb98a295a3dc3226ae9beb4d72180483af4ef9207f1b
Path kind: shared_cache
Requires model review: false

NOTE: Imported from a STEP model selected by parts_resolver.
      Verify upstream license and dimensional fit before manufacturing.
"""

import cadquery as cq


def make_std_ee_003_01() -> cq.Workplane:
    """GIS-EE-003-01: AE传感器 — imported from STEP file.

    Source: STEP:cache://ati/nano17.step
    """
    import os
    _here = os.path.dirname(os.path.abspath(__file__))
    _cache_rel = 'ati/nano17.step'
    _cache_root = os.environ.get("CAD_SPEC_GEN_STEP_CACHE")
    if _cache_root:
        _step_path = os.path.join(os.path.expanduser(_cache_root), _cache_rel)
    else:
        from pathlib import Path
        _step_path = os.path.join(str(Path.home()), ".cad-spec-gen", "step_cache", _cache_rel)
    _step_path = os.path.normpath(_step_path)
    if not os.path.isfile(_step_path):
        raise FileNotFoundError(
            f"STEP file missing for GIS-EE-003-01: {_step_path}")
    return cq.importers.importStep(_step_path)


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_003_01()
    p = os.path.join(out, "GIS-EE-003-01_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
