"""
伺服电机 (GIS-EE-001-05) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: motor | Make/Buy: 外购
Material: Maxon ECX SPEED 22L
Dimensions: {'d': 22, 'l': 68, 'shaft_d': 4, 'shaft_l': 14}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_001_05() -> cq.Workplane:
    """GIS-EE-001-05: 伺服电机 — simplified motor geometry."""
    # Simplified motor: cylinder + shaft
    body = cq.Workplane("XY").circle(11.0).extrude(68)
    # Output shaft
    body = body.faces(">Z").workplane().circle(2.0).extrude(14)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_001_05()
    p = os.path.join(out, "GIS-EE-001-05_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
