"""
LEMO插头 (GIS-EE-004-13) — 真实 STEP 导入件

Auto-generated by codegen/gen_std_parts.py via parts_resolver
Category: connector | Make/Buy: 外购
Material: FGG.0B.307
Source: STEP:cache://lemo/fgg_0b_307.step
Geometry source: REAL_STEP
Geometry quality: A
Validated: true
Hash: sha256:9cc0988de33776cb146a5d454e1854caf585ea685bcac80b1f4969956e9fff90
Path kind: shared_cache
Requires model review: false

NOTE: Imported from a STEP model selected by parts_resolver.
      Verify upstream license and dimensional fit before manufacturing.
"""

import cadquery as cq


def make_std_ee_004_13() -> cq.Workplane:
    """GIS-EE-004-13: LEMO插头 — imported from STEP file.

    Source: STEP:cache://lemo/fgg_0b_307.step
    """
    import os
    _here = os.path.dirname(os.path.abspath(__file__))
    _cache_rel = 'lemo/fgg_0b_307.step'
    _cache_root = os.environ.get("CAD_SPEC_GEN_STEP_CACHE")
    if _cache_root:
        _step_path = os.path.join(os.path.expanduser(_cache_root), _cache_rel)
    else:
        from pathlib import Path
        _step_path = os.path.join(str(Path.home()), ".cad-spec-gen", "step_cache", _cache_rel)
    _step_path = os.path.normpath(_step_path)
    if not os.path.isfile(_step_path):
        raise FileNotFoundError(
            f"STEP file missing for GIS-EE-004-13: {_step_path}")
    return cq.importers.importStep(_step_path)


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_004_13()
    p = os.path.join(out, "GIS-EE-004-13_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
