"""
配重块 (GIS-EE-004-10) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: other | Make/Buy: 外购
Material: 钨合金Φ14×13mm/120g
Dimensions: {'d': 14.0, 'l': 13.0}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_004_10() -> cq.Workplane:
    """GIS-EE-004-10: 配重块 — simplified other geometry."""
    # Generic cylindrical block
    body = cq.Workplane("XY").circle(7.0).extrude(13.0)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_004_10()
    p = os.path.join(out, "GIS-EE-004-10_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
