"""
LEMO插座 (GIS-EE-006-04) — 简化标准件几何

Auto-generated by codegen/gen_std_parts.py
Category: connector | Make/Buy: 外购
Material: EGG.0B.307
Dimensions: {'d': 10, 'l': 25}

NOTE: This is a simplified representation for visualization only.
      Not for manufacturing — actual part is purchased.
"""

import cadquery as cq


def make_std_ee_006_04() -> cq.Workplane:
    """GIS-EE-006-04: LEMO插座 — simplified connector geometry."""
    # Simplified round connector
    body = cq.Workplane("XY").circle(5.0).extrude(25)
    return body


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "..", "output")
    os.makedirs(out, exist_ok=True)
    r = make_std_ee_006_04()
    p = os.path.join(out, "GIS-EE-006-04_std.step")
    cq.exporters.export(r, p)
    print(f"Exported: {p}")
